### ISSUE TITLE
Need retry on some other API calls

### ISSUE THREAD

**Issue by stucka** [biglocalnews/warn-transformer#186]
There are retry routines for uploads and downloads, but not for this part:

2023-08-30 18:10:04,239 - warn_transformer.cli - Running download command
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/bin/warn-transformer", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn_transformer/cli.py", line 48, in download
    download_runner.run(download_dir, source)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn_transformer/download.py", line 32, in run
    p = c.get_project_by_name("WARN Act Notices")
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/bln/client.py", line 313, in get_project_by_name
    project_list = self.search_projects(lambda x: x["name"] == name)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/bln/client.py", line 406, in search_projects
    for v in self.effectiveProjectRoles():
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/bln/client.py", line 96, in effectiveProjectRoles
    return self._gql(q.query_effectiveProjectRoles)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/bln/client.py", line 55, in _gql
    raise APIException(err)
bln.exceptions.APIException: Internal Server Error
Error: Process completed with exit code 1.

**Comment by stucka** [comment]
Moving to bln-python-client
