### ISSUE TITLE
Intermittent build-release problem

### ISSUE THREAD

**Issue by stucka** [biglocalnews/warn-transformer#278]
Run make build-release
  __________
 |BIG🌲LOCAL|
 |&&& ======|
 |=== ======|  This is a Big Local News automation
 |=== == %%%|
 |[_] ======|        📦 Building release 📦
 |=== ===!##|
 |__________|

[05/31/24 15:26:58] WARNING  toml section missing        pyproject_reading.py:42
                             'pyproject.toml does not                           
                             contain a                                          
                             tool.setuptools_scm                                
                             section'                                           
Traceback (most recent call last):
  File "/home/runner/work/warn-transformer/warn-transformer/setup.py", line 47, in <module>
    setup(
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/dist.py", line 307, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/dist.py", line 658, in finalize_options
    ep(self)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools/dist.py", line 678, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 101, in version_keyword
    _assign_version(dist, config)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 53, in _assign_version
    maybe_version = _get_version(config, force_write_version_files=True)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 93, in _get_version
    parsed_version = parse_version(config)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 56, in parse_version
    or parse_scm_version(config)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 35, in parse_scm_version
    return _entrypoints.version_from_entrypoint(
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_entrypoints.py", line 55, in version_from_entrypoint
    maybe_version: version.ScmVersion | None = fn(root, config=config)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/git.py", line 211, in parse
    return _git_parse_inner(
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/git.py", line 272, in _git_parse_inner
    node_date = wd.get_head_date() or datetime.now(timezone.utc).date()
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/git.py", line 131, in get_head_date
    return res.parse_success(
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/_run_cmd.py", line 77, in parse_success
    return parse(self.stdout)
  File "/home/runner/.local/share/virtualenvs/warn-transformer-YifUlkSF/lib/python3.9/site-packages/setuptools_scm/git.py", line 121, in parse_timestamp
    return datetime.fromisoformat(timestamp_text).date()
ValueError: Invalid isoformat string: '2024-05-31T15:24:56Z'
make: *** [Makefile:116: build-release] Error 1
Error: Process completed with exit code 2.

**Comment by stucka** [comment]
Same kind of error, different string:
ValueError: Invalid isoformat string: '2024-06-10T20:55:18Z'
