### ISSUE TITLE
Error: "No project named WARN Act Notices found" on `make download`

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-transformer#72]
Following instructions in README, I set up project, set BLN API key, ran `make download` and got:

```
2022-02-23 19:54:12,877 - urllib3.connectionpool - https://api.biglocalnews.org:443 "POST /graphql HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/python/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspaces/warn-transformer/warn_transformer/download.py", line 52, in <module>
    run()
  File "/workspaces/warn-transformer/warn_transformer/download.py", line 32, in run
    p = c.get_project_by_name("WARN Act Notices")
  File "/workspaces/warn-transformer/.venv/lib/python3.8/site-packages/bln/client.py", line 435, in get_project_by_name
    raise ValueError(f"No project named {name} found")
ValueError: No project named WARN Act Notices found

make: *** [Makefile:76: download] Error 1
```

I'm able to view the project in BLN directory and download a file manually. Says here I'm a viewer, but of course I am not in the list of 15 explicitly added users.

**<img width="921" alt="Screen Shot 2022-02-23 at 2 57 02 PM" src="https://user-images.githubusercontent.com/1103467/155397900-23e1b52d-768b-41d9-ac0f-2e734dc658d4.png">**

**Comment by palewire** [comment]
Ah, I see. Thanks for pointing this out. I need to think about how we handle this.

**Comment by chriszs** [comment]
This was fixed for me by adding me to the project in Big Local News.
